apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-myportfolio-authinterface
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: kaniko-myportfolio-authinterface
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: [
          "--dockerfile=/godata/pipelines/myportfolio-authinterface/Dockerfile",
          "--context=/godata/pipelines/myportfolio-authinterface",
          "--destination=tfld-docker-prd-local.repo.14west.io/myportfolio-authinterface:1.13.1"
        ]
        volumeMounts:
        - mountPath: /godata
          name: gocdagent-data
        - mountPath: /kaniko/.docker/config.json
          name: docker-creds
          subPath: config.json
        env:
        - name: DESITINATION
          value: tfld-docker-prd-local.repo.14west.io/myportfolio-authinterface:1.13.1
      restartPolicy: Never   
      volumes:
      - name: gocdagent-data
        persistentVolumeClaim:
          claimName: gocdagent
      - name: docker-creds
        configMap:
          defaultMode: 420
          name: configcontent
      backoffLimit: 1
